development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV["MINIMALIST_DATABASE_DEV"] || "minimalist_development" %>
  username: <%= ENV["MINIMALIST_DATABASE_USER"] %>
  password: <%= ENV["MINIMALIST_DATABASE_PASSWORD"] %>
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: minimalist_test
  username: <%= ENV["MINIMALIST_DATABASE_USER"] %>
  password: <%= ENV["MINIMALIST_DATABASE_PASSWORD"] %>
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: minimalist
  username: <%= ENV["MINIMALIST_DATABASE_USER"] %>
  password: <%= ENV["MINIMALIST_DATABASE_PASSWORD"] %>
  pool: 5
  timeout: 5000