development:
  adapter: postgresql
  encoding: utf8
  database: db/development
  username: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: db/test
  username: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: db/production
  username: postgres
  pool: 5
  timeout: 5000